version: "3.3"
services:
  zokrates-sender:
      volumes:
          - ./proving-files:/app/output
          - ./circuits:/app/circuits
          - ./orchestration/common/write-vk.mjs:/app/write-vk.mjs
          - ./orchestration/common/db:/app/orchestration/common/db
      container_name: zokrates-sender
      networks:
          - starlight
      image: ghcr.io/eyblockchain/zokrates-worker-updated:latest
  timber-mongo:
      volumes:
          - timber-mongo-sender:/data/db
      environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=admin
          - MONGO_INITDB_DATABASE=merkle_tree
      container_name: timber-mongo-sender
      networks:
          - starlight
      image: starlight-mongo
  starlight-mongo:
      volumes:
          - zapp-mongo-sender:/data/db
      environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=admin
          - MONGO_INITDB_DATABASE=zapp_db
      container_name: zapp-mongo-sender
      networks:
          - starlight
      image: starlight-mongo
  timber:
      environment:
          - RPC_URL=<<your-value-here>>
          - LOG_LEVEL=debug
          - DB_URL=mongodb://admin:admin@timber-mongo:27017
          - HASH_TYPE=mimc
          - UNIQUE_LEAVES=true
          - SWAP_SHIELD_ADDRESS=<<your-value-here>>
          - DEPLOYER_HOST=<<your-value-here>>
          - DEPLOYER_PORT=<<your-value-here>>
          - DEFAULT_GAS_PRICE=<<your-value-here>>
          - INICIAL_BLOCK_TO_LISTEN_EVENTS=<<your-value-here>>
      ports:
          - 3100:80
      volumes:
          - ./build/contracts:/app/build/contracts
          - ./config_timber.js:/app/config/default.js
      networks:
          - starlight
      container_name: timber-sender
      image: timber
      depends_on:
        - timber-mongo
  zapp:
      ports:
          - 3000:3000
      volumes:
          - ./config/default.js:/app/config/default.js
          - ./orchestration/:/app/orchestration:delegated
          - ./orchestration/common/db/:/app/orchestration/common/db/
      environment:
          - SWAP_SHIELD_ADDRESS=0xCB5cb66001572a668e62E561b21f7F88A34bcC2a
          - ZOKRATES_URL=http://zokrates-sender
          - TIMBER_URL=http://timber-sender
          - DEFAULT_GAS_PRICE=<<your-value-here>>
          - RPC_URL=<<your-value-here>>
          - DEFAULT_ACCOUNT=<<your-value-here>>
          - KEY=<<your-value-here>>
          - ADMIN_ACCOUNT=<<your-value-here>>
          - ADMIN_KEY=<<your-value-here>>
          - MONGO_URL=mongodb://admin:admin@zapp-mongo-sender:27017
      networks:
          - starlight
      container_name: zapp-sender
      image: zapp-swapEscrow
      depends_on:
        - timber
        - starlight-mongo
        - zokrates-sender
networks:
  starlight:
    driver: bridge
volumes:
  timber-mongo-sender:
  zapp-mongo-sender: